import Swede_Crimson_Flame_Vertical from '../assets/images/Swede_Crimson_Flame_Vertical.png';
import Swede_Mandarin_Burst_Vertical from '../assets/images/Swede_Mandarin_Burst_Vertical.png';
import Swede_Dark_Storm_Vertical from '../assets/images/Swede_Dark_Storm_Vertical.png';
import Swede_Gold_Vertical from '../assets/images/Swede_Gold_Vertical.png';
import SuperSwedeCrimsonFlameVertical from '../assets/images/SuperSwedeCrimsonFlameVertical.png';
import SuperSwedeDarkStormVertical from '../assets/images/SuperSwedeDarkStormVertical.png';
import SuperSwedeFallSkyGlossVertical from '../assets/images/SuperSwedeFallSkyGlossVertical.png';
import SuperSwedeXtraSpecialOldPaleVertical from '../assets/images/SuperSwedeXtraSpecialOldPaleVertical.png';
import Alvar_Black_Gloss_Vertical from '../assets/images/Alvar_Black_Gloss_Vertical.png';
import Alvar_Swedish_Frost_Vertical from '../assets/images/Alvar_Swedish_Frost_Vertical.png';
import Alvar_Wild_Cherry_Transparent_Vertical from '../assets/images/Alvar_Wild_Cherry_Transparent_Vertical.png';
import Ultra_Max_Dark_Storm_Vertical from '../assets/images/Ultra_Max_Dark_Storm_Vertical.png';
import Ultra_Max_Fall_Sky_Satin_Vertical from '../assets/images/Ultra_Max_Fall_Sky_Satin_Vertical.png';
import Ultra_Max_Black_Satin_Vertical from '../assets/images/Ultra_Max_Black_Satin_Vertical.png';
import Ultra_Max_Golden_Eagle_Burst_Vertical from '../assets/images/Ultra_Max_Golden_Eagle_Burst_Vertical.png';
import Ultra_Max_Cosmic_Black_Burst_Satin_Vertical from '../assets/images/Ultra_Max_Cosmic_Black_Burst_Satin_Vertical.png';
import Ultra_Max_Milky_Mandarin_Satin_Vertical from '../assets/images/Ultra_Max_Milky_Mandarin_Satin_Vertical.png';
import Pat_Smear_Signature_Black_Gloss from '../assets/images/Pat_Smear_Signature_Black_Gloss.png';
import Artist_Project_Impala_Copperburst_Vertical from '../assets/images/Artist_Project_Impala_Copperburst_Vertical.png';
import Artist_Project_Viking_Gold_Top_Vertical from '../assets/images/Artist_Project_Viking_Gold_Top_Vertical.png';
import Artist_Project_Super_Viking_Trans_Brown_Vertical from '../assets/images/Artist_Project_Super_Viking_Trans_Brown_Vertical.png';
import Fantomen_Custom_Black_Gloss_Vertical from '../assets/images/Fantomen_Custom_Black_Gloss_Vertical.png';
import Fantomen_Custom_White_Gloss_Vertical from '../assets/images/Fantomen_Custom_White_Gloss_Vertical.png';
import Fantomen_White_Gloss_Vertical from '../assets/images/Fantomen_White_Gloss_Vertical.png';
import Fantomen_Black_Gloss_Vertical from '../assets/images/Fantomen_Black_Gloss_Vertical.png';
import Fantomen_Tobacco_Sunburst_Vertical from '../assets/images/Fantomen_Tobacco_Sunburst_Vertical.png';
import Retroscape_Impala_Black_Vertical from '../assets/images/Retroscape_Impala_Black_Vertical.png';
import Retroscape_Impala_Brown_Burst_Vertical from '../assets/images/Retroscape_Impala_Brown_Burst_Vertical.png';
import Retroscape_Impala_Cherry_Sunburst_Vertical from '../assets/images/Retroscape_Impala_Cherry_Sunburst_Vertical.png';
import Retroscape_Impala_Tobacco_Sunburst_Vertical from '../assets/images/Retroscape_Impala_Tobacco_Sunburst_Vertical.png';
import Retroscape_HIII_3_Tone_Sunburst_Vertical from '../assets/images/Retroscape_HIII_3_Tone_Sunburst_Vertical.png';
import Retroscape_HIII_Aged_Sky_Blue_Vertical from '../assets/images/Retroscape_HIII_Aged_Sky_Blue_Vertical.png';
import Retroscape_HIII_Black_Vertical from '../assets/images/Retroscape_HIII_Black_Vertical.png';
import Retroscape_HIII_White_Vertical from '../assets/images/Retroscape_HIII_White_Vertical.png';
import Super_Viking_Wild_Cherry_Transparent_Vertical from '../assets/images/Super_Viking_Wild_Cherry_Transparent_Vertical.png';
import Super_Viking_Black_Gloss_Vertical from '../assets/images/Super_Viking_Black_Gloss_Vertical.png';
import Super_Viking_Tobacco_Sunburst_Vertical from '../assets/images/Super_Viking_Tobacco_Sunburst_Vertical.png';
import Super_Viking_Dandy_Dandelion_Vertical from '../assets/images/Super_Viking_Dandy_Dandelion_Vertical.png';
import Super_Viking_Dark_Baltic_Sea_Vertical from '../assets/images/Super_Viking_Dark_Baltic_Sea_Vertical.png';
import Super_Viking_Mandarin_Flame_Vertical from '../assets/images/Super_Viking_Mandarin_Flame_Vertical.png';
import Super_Viking_Lefthand_Wild_Cherry_Transparent_Vertical from '../assets/images/Super_Viking_Lefthand_Wild_Cherry_Transparent_Vertical.png';
import Ultra_Swede_ESN_Black_Gloss_Vertical from '../assets/images/Ultra_Swede_ESN_Black_Gloss_Vertical.png';
import Ultra_Swede_ESN_Tobacco_Sunburst_Vertical from '../assets/images/Ultra_Swede_ESN_Tobacco_Sunburst_Vertical.png';
import Ultra_Swede_ESN_Wild_Cherry_Transparent_Vertical from '../assets/images/Ultra_Swede_ESN_Wild_Cherry_Transparent_Vertical.png';
import Ultra_Swede_Black_Gloss_Vertical from '../assets/images/Ultra_Swede_Black_Gloss_Vertical.png';
import Ultra_Swede_Burgundy_Burst_Vertical from '../assets/images/Ultra_Swede_Burgundy_Burst_Vertical.png';
import Ultra_Swede_Cosmic_Black_Burst_Vertical from '../assets/images/Ultra_Swede_Cosmic_Black_Burst_Vertical.png';
import Ultra_Swede_Worn_Denim_Vertical from '../assets/images/Ultra_Swede_Worn_Denim_Vertical.png';
import Viking_Black_Gloss_Vertical from '../assets/images/Viking_Black_Gloss_Vertical.png';
import Viking_Wild_Cherry_Transparent_Vertical from '../assets/images/Viking_Wild_Cherry_Transparent_Vertical.png';
import Viking_White_Gloss_Vertical from '../assets/images/Viking_White_Gloss_Vertical.png';
import Viking_Tobacco_Sunburst_Vertical from '../assets/images/Viking_Tobacco_Sunburst_Vertical.png';
import Viking67_Black_Gloss_Vertical from '../assets/images/Viking67_Black_Gloss_Vertical.png';
import Viking67_Wild_Cherry_Transparent_Vertical from '../assets/images/Viking67_Wild_Cherry_Transparent_Vertical.png';
import Viking_Deluxe_Baritone_Black_Gloss_Vertical from '../assets/images/Viking_Deluxe_Baritone_Black_Gloss_Vertical.png';
import Viking_Deluxe_12_Wild_Cherry_Transparent_Vertical from '../assets/images/Viking_Deluxe_12_Wild_Cherry_Transparent_Vertical.png';
import Tremar_Viking_Deluxe_Cloudy_Seas_Vertical from '../assets/images/Tremar_Viking_Deluxe_Cloudy_Seas_Vertical.png';
import Tremar_Viking_Deluxe_Wild_Cherry_Transparent_Vertical from '../assets/images/Tremar_Viking_Deluxe_Wild_Cherry_Transparent_Vertical.png';
import Tremar_Viking_Deluxe_Black_Gloss_Vertical from '../assets/images/Tremar_Viking_Deluxe_Black_Gloss_Vertical.png';
import HJ500_Black_Gloss_Vertical from '../assets/images/HJ500_Black_Gloss_Vertical.png';
import HJ500_Natural_Vertical from '../assets/images/HJ500_Natural_Vertical.png';
import Tremar_HJ500_Black_Gloss_Vertical from '../assets/images/Tremar_HJ500_Black_Gloss_Vertical.png';
import HJ800_Vintage_Sunburst_Vertical from '../assets/images/HJ800_Vintage_Sunburst_Vertical.png';
import HL550_Mahogany_Natural_Vertical from '../assets/images/HL550_Mahogany_Natural_Vertical.png';
import Super_Swede_Bass_Black_Gloss_Vertical from '../assets/images/Super_Swede_Bass_Black_Gloss_Vertical.png';
import Super_Swede_Bass_Natural_Mahogany_Vertical from '../assets/images/Super_Swede_Bass_Natural_Mahogany_Vertical.png';
import Swede_Bass_Black_Gloss_Vertical from '../assets/images/Swede_Bass_Black_Gloss_Vertical.png';
import Swede_Bass_Lefthand_Wild_Cherry_Transparent_Vertical from '../assets/images/Swede_Bass_Lefthand_Wild_Cherry_Transparent_Vertical.png';
import Swede_Bass_Tobacco_Sunburst_Vertical from '../assets/images/Swede_Bass_Tobacco_Sunburst_Vertical.png';
import Swede_Bass_White_Gloss_Vertical from '../assets/images/Swede_Bass_White_Gloss_Vertical.png';
import Swede_Bass_Wild_Cherry_Transparent_Vertical from '../assets/images/Swede_Bass_Wild_Cherry_Transparent_Vertical.png';
import Viking_Bass_Black_Gloss_Vertical from '../assets/images/Viking_Bass_Black_Gloss_Vertical.png';
import Viking_Bass_Wild_Cherry_Transparent_Vertical from '../assets/images/Viking_Bass_Wild_Cherry_Transparent_Vertical.png';
import Viking_Bass_Tobacco_Sunburst_Vertical from '../assets/images/Viking_Bass_Tobacco_Sunburst_Vertical.png';
import Viking_Bass_White_Gloss_Vertical from '../assets/images/Viking_Bass_White_Gloss_Vertical.png';
import H8_II_Wild_Cherry_Transparent_Vertical from '../assets/images/H8_II_Wild_Cherry_Transparent_Vertical.png';
import H8_II_Black_Gloss_Vertical from '../assets/images/H8_II_Black_Gloss_Vertical.png';
import H8_II_Tobacco_Sunburst_Vertical from '../assets/images/H8_II_Tobacco_Sunburst_Vertical.png';
import Acoustic_Orsa_Dreadnought_Vertical from '../assets/images/Acoustic_Orsa_Dreadnought_Vertical.png';
import Acoustic_Orsa_Dreadnought_CE_Vertical from '../assets/images/Acoustic_Orsa_Dreadnought_CE_Vertical.png';
import Acoustic_Orsa_GA_Vertical from '../assets/images/Acoustic_Orsa_GA_Vertical.png';
import Acoustic_Orsa_Grand_Auditorium_CE_Vertical from '../assets/images/Acoustic_Orsa_Grand_Auditorium_CE_Vertical.png';
import Acoustic_Elfdalia_II_Dreadnought_Natural_Ceder_Vertical from '../assets/images/Acoustic_Elfdalia_II_Dreadnought_Natural_Ceder_Vertical.png';
import Acoustic_Elfdalia_II_Dreadnought_CE_Natural_Ceder_Vertical from '../assets/images/Acoustic_Elfdalia_II_Dreadnought_CE_Natural_Ceder_Vertical.png';
import Acoustic_Elfdalia_II_Grand_Auditorium_Natural_Ceder_Vertical from '../assets/images/Acoustic_Elfdalia_II_Grand_Auditorium_Natural_Ceder_Vertical.png';
import Acoustic_Elfdalia_II_Grand_Auditorium_CE_Natural_Ceder_Vertical from '../assets/images/Acoustic_Elfdalia_II_Grand_Auditorium_CE_Natural_Ceder_Vertical.png';
import Acoustic_Mora_II_Concert_Vertical from '../assets/images/Acoustic_Mora_II_Concert_Vertical.png';
import Acoustic_Mora_II_Concert_CE_Vertical from '../assets/images/Acoustic_Mora_II_Concert_CE_Vertical.png';
import Acoustic_Mora_II_Dreadnought_Vertical from '../assets/images/Acoustic_Mora_II_Dreadnought_Vertical.png';
import Acoustic_Mora_II_Dreadnought_CE_Vertical from '../assets/images/Acoustic_Mora_II_Dreadnought_CE_Vertical.png';

import { nanoid } from '@reduxjs/toolkit';

const productsList = [
  {
    src: Swede_Crimson_Flame_Vertical,
    brand: 'Hagstrom',
    name: 'Swede',
    color: 'Crimson Flame',
    info: '/MoreInfoSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Mandarin_Burst_Vertical,
    brand: 'Hagstrom',
    name: 'Swede',
    color: 'Mandarin Burst',
    info: '/MoreInfoSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Dark_Storm_Vertical,
    brand: 'Hagstrom',
    name: 'Swede',
    color: 'Dark Storm',
    info: '/MoreInfoSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Gold_Vertical,
    brand: 'Hagstrom',
    name: 'Swede',
    color: 'Gold',
    info: '/MoreInfoSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: SuperSwedeCrimsonFlameVertical,
    brand: 'Hagstrom',
    name: 'Super Swede',
    color: 'Crimson Flame',
    info: '/MoreInfoSuperSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: SuperSwedeDarkStormVertical,
    brand: 'Hagstrom',
    name: 'Super Swede',
    color: 'Dark Storm',
    info: '/MoreInfoSuperSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: SuperSwedeFallSkyGlossVertical,
    brand: 'Hagstrom',
    name: 'Super Swede',
    color: 'Fall Sky Gloss',
    info: '/MoreInfoSuperSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: SuperSwedeXtraSpecialOldPaleVertical,
    brand: 'Hagstrom',
    name: 'Super Swede',
    color: 'X-tra Special Old Pale',
    info: '/MoreInfoSuperSwede',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Alvar_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Alvar',
    color: 'Black Gloss',
    info: '/MoreInfoAlvar',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Alvar_Swedish_Frost_Vertical,
    brand: 'Hagstrom',
    name: 'Alvar',
    color: 'Swedish Frost',
    info: '/MoreInfoAlvar',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Alvar_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Alvar',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoAlvar',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Max_Dark_Storm_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Max',
    color: 'Dark Storm',
    info: '/MoreInfoUltraMax',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Max_Fall_Sky_Satin_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Max',
    color: 'Fall Sky Satin',
    info: '/MoreInfoUltraMax',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Max_Black_Satin_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Max',
    color: 'Black Satin',
    info: '/MoreInfoUltraMax',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Max_Golden_Eagle_Burst_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Max',
    color: 'Golden Eagle Burst',
    info: '/MoreInfoUltraMax',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Max_Cosmic_Black_Burst_Satin_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Max',
    color: 'Cosmic Black Burst Satin',
    info: '/MoreInfoUltraMax',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Max_Milky_Mandarin_Satin_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Max',
    color: 'Milky Mandarin Satin',
    info: '/MoreInfoUltraMax',
    price: '3500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Pat_Smear_Signature_Black_Gloss,
    brand: 'Hagstrom',
    name: 'Pat Smear Signature',
    color: 'Black Gloss',
    info: '/MoreInfoPatSmear',
    price: '1100',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Artist_Project_Impala_Copperburst_Vertical,
    brand: 'Hagstrom',
    name: 'Artist Project Impala',
    color: 'Copperburst',
    info: '/MoreInfoImpalaCopperburst',
    price: '1200',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Artist_Project_Viking_Gold_Top_Vertical,
    brand: 'Hagstrom',
    name: 'Artist Project Viking',
    color: 'Gold Top',
    info: '/MoreInfoVikingGoldTop',
    price: '1200',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Artist_Project_Super_Viking_Trans_Brown_Vertical,
    brand: 'Hagstrom',
    name: 'Artist Project Super Viking',
    color: 'Transparent Brown',
    info: '/MoreInfoSuperVikingTransBrown',
    price: '1200',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Fantomen_Custom_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Fantomen Custom',
    color: 'Black Gloss',
    info: '/MoreInfoFantomenCustom',
    price: '1300',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Fantomen_Custom_White_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Fantomen Custom',
    color: 'White Gloss',
    info: '/MoreInfoFantomenCustom',
    price: '1300',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Fantomen_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Fantomen',
    color: 'Black Gloss',
    info: '/MoreInfoFantomen',
    price: '1300',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Fantomen_White_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Fantomen',
    color: 'White Gloss',
    info: '/MoreInfoFantomen',
    price: '1300',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Fantomen_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Fantomen',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoFantomen',
    price: '1300',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_Impala_Black_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape Impala',
    color: 'Black',
    info: '/MoreInfoRetroScapeImpala',
    price: '1150',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_Impala_Brown_Burst_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape Impala',
    color: 'Brown Burst',
    info: '/MoreInfoRetroScapeImpala',
    price: '1150',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_Impala_Cherry_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape Impala',
    color: 'Cherry Sunburst',
    info: '/MoreInfoRetroScapeImpala',
    price: '1150',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_Impala_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape Impala',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoRetroScapeImpala',
    price: '1150',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_HIII_3_Tone_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape H-III',
    color: '3 Tone Sunburst',
    info: '/MoreInfoRetroScapeHIII',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_HIII_Aged_Sky_Blue_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape H-III',
    color: 'Aged Sky Blue',
    info: '/MoreInfoRetroScapeHIII',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_HIII_Black_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape H-III',
    color: 'Black',
    info: '/MoreInfoRetroScapeHIII',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Retroscape_HIII_White_Vertical,
    brand: 'Hagstrom',
    name: 'Retroscape H-III',
    color: 'White',
    info: '/MoreInfoRetroScapeHIII',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Viking_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Super Viking',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoSuperViking',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Viking_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Super Viking',
    color: 'Black Gloss',
    info: '/MoreInfoSuperViking',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Viking_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Super Viking',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoSuperViking',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Viking_Dandy_Dandelion_Vertical,
    brand: 'Hagstrom',
    name: 'Super Viking',
    color: 'Dandy Dandelion',
    info: '/MoreInfoSuperViking',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Viking_Dark_Baltic_Sea_Vertical,
    brand: 'Hagstrom',
    name: 'Super Viking',
    color: 'Dark Baltic Sea',
    info: '/MoreInfoSuperViking',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Viking_Mandarin_Flame_Vertical,
    brand: 'Hagstrom',
    name: 'Super Viking',
    color: 'Mandarin Flame',
    info: '/MoreInfoSuperViking',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Viking_Lefthand_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Super Viking Lefthand',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoSuperViking',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Swede_ESN_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Swede ESN',
    color: 'Black Gloss',
    info: '/MoreInfoUltraSwedeESN',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Swede_ESN_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Swede ESN',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoUltraSwedeESN',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Swede_ESN_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Swede ESN',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoUltraSwedeESN',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Swede_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Swede',
    color: 'Black Gloss',
    info: '/MoreInfoUltraSwede',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Swede_Burgundy_Burst_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Swede',
    color: 'Burgundy Burst',
    info: '/MoreInfoUltraSwede',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Swede_Cosmic_Black_Burst_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Swede',
    color: 'Cosmic Black Burst',
    info: '/MoreInfoUltraSwede',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Ultra_Swede_Worn_Denim_Vertical,
    brand: 'Hagstrom',
    name: 'Ultra Swede',
    color: 'Worn Denim',
    info: '/MoreInfoUltraSwede',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Viking®',
    color: 'Black Gloss',
    info: '/MoreInfoViking',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Viking®',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoViking',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_White_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Viking®',
    color: 'White Gloss',
    info: '/MoreInfoViking',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Viking®',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoViking',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking67_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: "'67 Viking® II",
    color: 'Black Gloss',
    info: '/MoreInfoViking67',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking67_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: "'67 Viking® II",
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoViking67',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Deluxe_Baritone_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Viking® Deluxe Baritone',
    color: 'Black Gloss',
    info: '/MoreInfoVikingDeluxeBaritone',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Deluxe_12_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Viking® Deluxe 12-String',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoVikingDeluxe12',
    price: '1450',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Tremar_Viking_Deluxe_Cloudy_Seas_Vertical,
    brand: 'Hagstrom',
    name: 'Tremar Viking® Deluxe',
    color: 'Cloudy Seas',
    info: '/MoreInfoTremarVikingDeluxe',
    price: '1550',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Tremar_Viking_Deluxe_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Tremar Viking® Deluxe',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoTremarVikingDeluxe',
    price: '1550',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Tremar_Viking_Deluxe_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Tremar Viking® Deluxe',
    color: 'Black Gloss',
    info: '/MoreInfoTremarVikingDeluxe',
    price: '1550',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: HJ500_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'HJ500',
    color: 'Black Gloss',
    info: '/MoreInfoHJ500',
    price: '1500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: HJ500_Natural_Vertical,
    brand: 'Hagstrom',
    name: 'HJ500',
    color: 'Natural',
    info: '/MoreInfoHJ500',
    price: '1500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Tremar_HJ500_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Tremar HJ500',
    color: 'Black Gloss',
    info: '/MoreInfoTremarHJ500',
    price: '1600',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: HJ800_Vintage_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'HJ800',
    color: 'Vintage Sunburst',
    info: '/MoreInfoHJ800',
    price: '1500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: HL550_Mahogany_Natural_Vertical,
    brand: 'Hagstrom',
    name: 'HL550',
    color: 'Mahogany Natural',
    info: '/MoreInfoHL550',
    price: '1500',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Swede_Bass_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Super Swede Bass',
    color: 'Black Gloss',
    info: '/MoreInfoSuperSwedeBass',
    price: '1200',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Super_Swede_Bass_Natural_Mahogany_Vertical,
    brand: 'Hagstrom',
    name: 'Super Swede Bass',
    color: 'Mahogany Natural',
    info: '/MoreInfoSuperSwedeBass',
    price: '1200',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Bass_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Swede Bass',
    color: 'Black Gloss',
    info: '/MoreInfoSwedeBass',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Bass_Lefthand_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Swede Bass Lefthand',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoSwedeBass',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Bass_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Swede Bass',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoSwedeBass',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Bass_White_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Swede Bass',
    color: 'White Gloss',
    info: '/MoreInfoSwedeBass',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Swede_Bass_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Swede Bass',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoSwedeBass',
    price: '1250',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Bass_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Viking® Bass',
    color: 'Black Gloss',
    info: '/MoreInfoVikingBass',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Bass_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'Viking® Bass',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoVikingBass',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Bass_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'Viking® Bass',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoVikingBass',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Viking_Bass_White_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'Viking® Bass',
    color: 'White Gloss',
    info: '/MoreInfoVikingBass',
    price: '1350',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: H8_II_Wild_Cherry_Transparent_Vertical,
    brand: 'Hagstrom',
    name: 'H8-II Bass',
    color: 'Wild Cherry Transparent',
    info: '/MoreInfoH8IIBass',
    price: '1750',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: H8_II_Black_Gloss_Vertical,
    brand: 'Hagstrom',
    name: 'H8-II Bass',
    color: 'Black Gloss',
    info: '/MoreInfoH8IIBass',
    price: '1750',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: H8_II_Tobacco_Sunburst_Vertical,
    brand: 'Hagstrom',
    name: 'H8-II Bass',
    color: 'Tobacco Sunburst',
    info: '/MoreInfoH8IIBass',
    price: '1750',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Orsa_Dreadnought_Vertical,
    brand: 'Hagstrom',
    name: 'Orsa Dreadnought',
    color: 'Natural',
    info: '/MoreInfoOrsaDreadnought',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Orsa_Dreadnought_CE_Vertical,
    brand: 'Hagstrom',
    name: 'Orsa Dreadnought CE',
    color: 'Natural',
    info: '/MoreInfoOrsaDreadnoughtCE',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Orsa_GA_Vertical,
    brand: 'Hagstrom',
    name: 'Orsa Grand Auditorium',
    color: 'Natural',
    info: '/MoreInfoOrsaGrandAuditorium',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Orsa_Grand_Auditorium_CE_Vertical,
    brand: 'Hagstrom',
    name: 'Orsa Grand Auditorium CE',
    color: 'Natural',
    info: '/MoreInfoOrsaGrandAuditoriumCE',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Elfdalia_II_Dreadnought_Natural_Ceder_Vertical,
    brand: 'Hagstrom',
    name: 'Elfdalia II Dreadnought',
    color: 'Natural Ceder',
    info: '/MoreInfoElfdaliaIIDreadnought',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Elfdalia_II_Dreadnought_CE_Natural_Ceder_Vertical,
    brand: 'Hagstrom',
    name: 'Elfdalia II Dreadnought CE',
    color: 'Natural Ceder',
    info: '/MoreInfoElfdaliaIIDreadnoughtCE',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Elfdalia_II_Grand_Auditorium_Natural_Ceder_Vertical,
    brand: 'Hagstrom',
    name: 'Elfdalia II Grand Auditorium',
    color: 'Natural Ceder',
    info: '/MoreInfoElfdaliaIIGrandAuditorium',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Elfdalia_II_Grand_Auditorium_CE_Natural_Ceder_Vertical,
    brand: 'Hagstrom',
    name: 'Elfdalia II Grand Auditorium CE',
    color: 'Natural Ceder',
    info: '/MoreInfoElfdaliaIIGrandAuditoriumCE',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Mora_II_Concert_Vertical,
    brand: 'Hagstrom',
    name: 'Mora II Concert',
    color: 'Natural Mahogany',
    info: '/MoreInfoMoraIIConcert',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Mora_II_Concert_CE_Vertical,
    brand: 'Hagstrom',
    name: 'Mora II Concert CE',
    color: 'Natural Mahogany',
    info: '/MoreInfoMoraIIConcertCE',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Mora_II_Dreadnought_Vertical,
    brand: 'Hagstrom',
    name: 'Mora II Dreadnought',
    color: 'Natural Mahogany',
    info: '/MoreInfoMoraIIDreadnought',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
  {
    src: Acoustic_Mora_II_Dreadnought_CE_Vertical,
    brand: 'Hagstrom',
    name: 'Mora II Dreadnought CE',
    color: 'Natural Mahogany',
    info: '/MoreInfoMoraIIDreadnoughtCE',
    price: '900',
    quantity: 1,
    id: nanoid(),
  },
];

export default productsList;
